package com.example.atak2drone.domain.interfaces

import com.example.atak2drone.domain.model.MissionPlan
import com.example.atak2drone.domain.model.MissionType
import com.example.atak2drone.domain.model.SurveyConfig
import com.example.atak2drone.model.Coordinate

/**
 * Open/Closed Principle (OCP) & Liskov Substitution Principle (LSP):
 * Strategy interface allowing pluggable mission planning algorithms
 * (e.g. Vertex perimeter, Lawnmower survey, Corridor, Multi-Grid).
 */
interface IMissionStrategy {
    /**
     * The type of mission generated by this strategy.
     */
    val missionType: MissionType

    /**
     * Generates a complete flight mission plan from an input polygon boundary and survey configuration.
     *
     * @param polygon The bounding polygon coordinates.
     * @param config The survey parameters (altitude, speed, overlap, FOV, angle override).
     * @return Generated [MissionPlan] containing ordered waypoints and optimization metrics.
     */
    fun generatePlan(polygon: List<Coordinate>, config: SurveyConfig): MissionPlan
}
